use_frameworks!
platform :ios, '9.0'

target 'chabokstarterrnbridge' do

  # Pods for AwesomeProject
  pod 'ChabokPush'

end

target 'NotificationService' do
  use_frameworks!
  
  pod 'ChabokPush'
  
end
